"""Texte der Branchen-Flyer in DE/IT/EN (04.10.2026). Nur Leistungen, die Vecom baut — keine Erfolgsversprechen.
   Je Branche: gruppe (wie app/flyer/liste.php), titel, sub, vier Punkte, slogan."""
G = {  # feste Teile
 'websites_fuer': {'de': 'WEBSITES FÜR', 'it': 'SITI WEB PER', 'en': 'WEBSITES FOR'},
 'cta': {'de': 'Jetzt beraten lassen', 'it': 'Richieda una consulenza', 'en': 'Get advice now'},
 'scan': {'de': 'Code scannen', 'it': 'Scansioni il codice', 'en': 'Scan the code'},
}
B = {
 'handwerk': ('bau', {'de': 'BAU & HANDWERK', 'it': 'EDILIZIA & ARTIGIANI', 'en': 'CONSTRUCTION & TRADES'},
   {'de': 'Ihre Projekte digital präsentiert.', 'it': 'I suoi progetti presentati online.', 'en': 'Your projects presented online.'},
   [{'de': 'Projekte & Referenzen', 'it': 'Progetti e referenze', 'en': 'Projects & references'},
    {'de': 'Leistungen übersichtlich', 'it': 'Servizi chiari', 'en': 'Clear list of services'},
    {'de': 'Anfrageformular', 'it': 'Modulo di richiesta', 'en': 'Enquiry form'},
    {'de': 'Für alle Geräte gebaut', 'it': 'Per tutti i dispositivi', 'en': 'Built for every device'}],
   {'de': 'Starke Arbeit verdient eine starke Website.', 'it': 'Un buon lavoro merita un buon sito.', 'en': 'Great work deserves a great website.'}),
 'arztpraxis': ('gesundheit', {'de': 'ÄRZTE & PRAXEN', 'it': 'MEDICI & STUDI', 'en': 'DOCTORS & PRACTICES'},
   {'de': 'Vertrauen. Kompetenz. Modern präsentiert.', 'it': 'Fiducia e competenza, in modo moderno.', 'en': 'Trust and expertise, presented well.'},
   [{'de': 'Terminanfrage online', 'it': 'Richiesta appuntamento online', 'en': 'Online appointment requests'},
    {'de': 'Leistungen verständlich erklärt', 'it': 'Prestazioni spiegate con chiarezza', 'en': 'Services clearly explained'},
    {'de': 'Team & Praxis vorgestellt', 'it': 'Team e studio presentati', 'en': 'Team and practice introduced'},
    {'de': 'Datenschutz von Anfang an', 'it': 'Privacy fin dall’inizio', 'en': 'Privacy from the start'}],
   {'de': 'Vertrauen beginnt online.', 'it': 'La fiducia inizia online.', 'en': 'Trust starts online.'}),
 'immobilien': ('handel', {'de': 'IMMOBILIEN', 'it': 'IMMOBILIARE', 'en': 'REAL ESTATE'},
   {'de': 'Objekte, die begeistern.', 'it': 'Immobili che conquistano.', 'en': 'Properties that impress.'},
   [{'de': 'Hochwertige Objektseiten', 'it': 'Schede immobili curate', 'en': 'High-quality listings'},
    {'de': 'Virtuelle 3D-Rundgänge', 'it': 'Tour virtuali in 3D', 'en': 'Virtual 3D tours'},
    {'de': 'Kontakt- und Anfrageformulare', 'it': 'Moduli di contatto e richiesta', 'en': 'Contact and enquiry forms'},
    {'de': 'Für Käufer und Mieter', 'it': 'Per acquirenti e inquilini', 'en': 'For buyers and tenants'}],
   {'de': 'Immobilien digital erleben.', 'it': 'Vivere gli immobili online.', 'en': 'Experience properties online.'}),
 'kosmetik': ('gesundheit', {'de': 'BEAUTY & WELLNESS', 'it': 'BELLEZZA & BENESSERE', 'en': 'BEAUTY & WELLNESS'},
   {'de': 'Schönheit digital in Szene gesetzt.', 'it': 'La bellezza messa in scena online.', 'en': 'Beauty, beautifully presented online.'},
   [{'de': 'Elegantes Design', 'it': 'Design elegante', 'en': 'Elegant design'},
    {'de': 'Terminanfrage online', 'it': 'Prenotazione online', 'en': 'Online booking requests'},
    {'de': 'Behandlungen im Überblick', 'it': 'Trattamenti in sintesi', 'en': 'Treatments at a glance'},
    {'de': 'Bilder & Videos', 'it': 'Foto e video', 'en': 'Photos & videos'}],
   {'de': 'Entspannung beginnt online.', 'it': 'Il relax inizia online.', 'en': 'Relaxation starts online.'}),
 'restaurant': ('gast', {'de': 'RESTAURANTS', 'it': 'RISTORANTI', 'en': 'RESTAURANTS'},
   {'de': 'Genuss digital erleben.', 'it': 'Il gusto, anche online.', 'en': 'Taste, online too.'},
   [{'de': 'Speisekarte online', 'it': 'Menù online', 'en': 'Menu online'},
    {'de': 'Reservierungsanfrage', 'it': 'Richiesta di prenotazione', 'en': 'Reservation requests'},
    {'de': 'Bilder, die Appetit machen', 'it': 'Foto che fanno venire fame', 'en': 'Mouth-watering photos'},
    {'de': 'Events & Neuigkeiten', 'it': 'Eventi e novità', 'en': 'Events & news'}],
   {'de': 'Mehr als eine Speisekarte. Ein Erlebnis.', 'it': 'Più di un menù. Un’esperienza.', 'en': 'More than a menu. An experience.'}),
 'hotel': ('gast', {'de': 'HOTELS & FERIENWOHNUNGEN', 'it': 'HOTEL & CASE VACANZA', 'en': 'HOTELS & HOLIDAY HOMES'},
   {'de': 'Gäste begeistern, direkt anfragen lassen.', 'it': 'Ospiti entusiasti, richieste dirette.', 'en': 'Delight guests, take direct enquiries.'},
   [{'de': 'Zimmer & Preise', 'it': 'Camere e prezzi', 'en': 'Rooms & rates'},
    {'de': 'Anfrage- oder Buchungsformular', 'it': 'Modulo di richiesta o prenotazione', 'en': 'Enquiry or booking form'},
    {'de': 'Galerien & 3D-Rundgänge', 'it': 'Gallerie e tour 3D', 'en': 'Galleries & 3D tours'},
    {'de': 'Lage & Umgebung', 'it': 'Posizione e dintorni', 'en': 'Location & surroundings'}],
   {'de': 'Urlaub beginnt online.', 'it': 'La vacanza inizia online.', 'en': 'Holidays start online.'}),
 'fitness': ('gesundheit', {'de': 'FITNESS & SPORT', 'it': 'FITNESS & SPORT', 'en': 'FITNESS & SPORT'},
   {'de': 'Motivation digital erleben.', 'it': 'Motivazione, anche online.', 'en': 'Motivation, online too.'},
   [{'de': 'Kurspläne & Trainer', 'it': 'Corsi e istruttori', 'en': 'Class schedules & trainers'},
    {'de': 'Mitgliedschaften im Überblick', 'it': 'Abbonamenti in sintesi', 'en': 'Memberships at a glance'},
    {'de': 'Video & Trainingsbereiche', 'it': 'Video e aree di allenamento', 'en': 'Video & training areas'},
    {'de': 'Anmeldung zum Probetraining', 'it': 'Iscrizione alla prova', 'en': 'Trial session sign-up'}],
   {'de': 'Mehr als Training. Eine Community.', 'it': 'Più di un allenamento. Una community.', 'en': 'More than training. A community.'}),
 'tourismus': ('gast', {'de': 'REISEN & TOURISMUS', 'it': 'VIAGGI & TURISMO', 'en': 'TRAVEL & TOURISM'},
   {'de': 'Erlebnisse digital präsentiert.', 'it': 'Esperienze presentate online.', 'en': 'Experiences presented online.'},
   [{'de': 'Reiseangebote & Touren', 'it': 'Offerte e tour', 'en': 'Trips & tours'},
    {'de': 'Bilder & Videos', 'it': 'Foto e video', 'en': 'Photos & videos'},
    {'de': 'Anfrage- oder Buchungsformular', 'it': 'Modulo di richiesta o prenotazione', 'en': 'Enquiry or booking form'},
    {'de': 'Mehrsprachig', 'it': 'Multilingue', 'en': 'Multilingual'}],
   {'de': 'Die Welt nur einen Klick entfernt.', 'it': 'Il mondo a un clic.', 'en': 'The world, one click away.'}),
 'kanzlei': ('beratung', {'de': 'ANWÄLTE & KANZLEIEN', 'it': 'AVVOCATI & STUDI LEGALI', 'en': 'LAWYERS & LAW FIRMS'},
   {'de': 'Seriös. Kompetent. Vertrauenswürdig.', 'it': 'Serietà, competenza, fiducia.', 'en': 'Serious. Competent. Trustworthy.'},
   [{'de': 'Rechtsgebiete klar dargestellt', 'it': 'Aree di competenza chiare', 'en': 'Practice areas clearly shown'},
    {'de': 'Team & Fachgebiete', 'it': 'Team e specializzazioni', 'en': 'Team & specialisms'},
    {'de': 'Einfache Kontaktaufnahme', 'it': 'Contatto semplice', 'en': 'Easy to get in touch'},
    {'de': 'Fachartikel & Aktuelles', 'it': 'Articoli e novità', 'en': 'Articles & news'}],
   {'de': 'Vertrauen beginnt online.', 'it': 'La fiducia inizia online.', 'en': 'Trust starts online.'}),
 'solar': ('bau', {'de': 'SOLAR & ENERGIE', 'it': 'SOLARE & ENERGIA', 'en': 'SOLAR & ENERGY'},
   {'de': 'Nachhaltige Lösungen digital präsentiert.', 'it': 'Soluzioni sostenibili presentate online.', 'en': 'Sustainable solutions presented online.'},
   [{'de': 'Leistungen & Vorteile', 'it': 'Servizi e vantaggi', 'en': 'Services & benefits'},
    {'de': 'Projekte & Referenzen', 'it': 'Progetti e referenze', 'en': 'Projects & references'},
    {'de': 'Förderungen erklärt', 'it': 'Incentivi spiegati', 'en': 'Subsidies explained'},
    {'de': 'Anfrageformular', 'it': 'Modulo di richiesta', 'en': 'Enquiry form'}],
   {'de': 'Heute in die Zukunft investieren.', 'it': 'Investire oggi nel futuro.', 'en': 'Invest in the future today.'}),
 'industrie': ('handel', {'de': 'INDUSTRIE & MASCHINENBAU', 'it': 'INDUSTRIA & MECCANICA', 'en': 'INDUSTRY & ENGINEERING'},
   {'de': 'Technik digital präsentiert.', 'it': 'Tecnica presentata online.', 'en': 'Engineering presented online.'},
   [{'de': 'Produkte & Lösungen', 'it': 'Prodotti e soluzioni', 'en': 'Products & solutions'},
    {'de': '3D-Modelle und Animationen', 'it': 'Modelli 3D e animazioni', 'en': '3D models and animations'},
    {'de': 'Mehrsprachig für den Export', 'it': 'Multilingue per l’export', 'en': 'Multilingual for export'},
    {'de': 'Downloads & Datenblätter', 'it': 'Download e schede tecniche', 'en': 'Downloads & data sheets'}],
   {'de': 'Technik, die man versteht.', 'it': 'Tecnica che si capisce.', 'en': 'Engineering people understand.'}),
 'landwirtschaft': ('handel', {'de': 'LANDWIRTSCHAFT & AGRAR', 'it': 'AGRICOLTURA', 'en': 'FARMING & AGRICULTURE'},
   {'de': 'Tradition trifft digitale Zukunft.', 'it': 'La tradizione incontra il digitale.', 'en': 'Tradition meets the digital future.'},
   [{'de': 'Produkte & Leistungen', 'it': 'Prodotti e servizi', 'en': 'Products & services'},
    {'de': 'Hofladen & Direktverkauf', 'it': 'Spaccio e vendita diretta', 'en': 'Farm shop & direct sales'},
    {'de': 'Bilder & Videos vom Hof', 'it': 'Foto e video dall’azienda', 'en': 'Photos & videos from the farm'},
    {'de': 'Für alle Geräte gebaut', 'it': 'Per tutti i dispositivi', 'en': 'Built for every device'}],
   {'de': 'Vom Feld ins Netz.', 'it': 'Dal campo alla rete.', 'en': 'From the field to the web.'}),
 'autohaus': ('handel', {'de': 'AUTOHÄUSER', 'it': 'CONCESSIONARIE', 'en': 'CAR DEALERS'},
   {'de': 'Fahrzeuge ins beste Licht gerückt.', 'it': 'Veicoli nella luce migliore.', 'en': 'Vehicles in their best light.'},
   [{'de': '3D-Fahrzeugpräsentation', 'it': 'Presentazione 3D dei veicoli', 'en': '3D vehicle presentation'},
    {'de': 'Fahrzeugbestand online', 'it': 'Parco auto online', 'en': 'Vehicle stock online'},
    {'de': 'Probefahrt-Anfrage', 'it': 'Richiesta prova su strada', 'en': 'Test drive requests'},
    {'de': 'Service & Werkstatt', 'it': 'Assistenza e officina', 'en': 'Service & workshop'}],
   {'de': 'Der Showroom, der nie schließt.', 'it': 'Lo showroom sempre aperto.', 'en': 'The showroom that never closes.'}),
 'steuerberater': ('beratung', {'de': 'STEUERBERATER', 'it': 'COMMERCIALISTI', 'en': 'TAX ADVISERS'},
   {'de': 'Professionell. Klar. Vertrauenswürdig.', 'it': 'Professionali, chiari, affidabili.', 'en': 'Professional. Clear. Trustworthy.'},
   [{'de': 'Leistungen klar präsentiert', 'it': 'Servizi presentati con chiarezza', 'en': 'Services clearly presented'},
    {'de': 'Mandantenanfragen online', 'it': 'Richieste clienti online', 'en': 'Client enquiries online'},
    {'de': 'Team & Kanzlei', 'it': 'Team e studio', 'en': 'Team & firm'},
    {'de': 'Datenschutz von Anfang an', 'it': 'Privacy fin dall’inizio', 'en': 'Privacy from the start'}],
   {'de': 'Ordnung, die man sieht.', 'it': 'Ordine che si vede.', 'en': 'Order you can see.'}),
 'logistik': ('handel', {'de': 'LOGISTIK & TRANSPORT', 'it': 'LOGISTICA & TRASPORTI', 'en': 'LOGISTICS & TRANSPORT'},
   {'de': 'Modern. Zuverlässig. Unterwegs.', 'it': 'Moderni, affidabili, in movimento.', 'en': 'Modern. Reliable. On the move.'},
   [{'de': 'Unternehmenspräsentation', 'it': 'Presentazione aziendale', 'en': 'Company presentation'},
    {'de': 'Leistungen & Fuhrpark', 'it': 'Servizi e flotta', 'en': 'Services & fleet'},
    {'de': 'Anfragen für Aufträge', 'it': 'Richieste di trasporto', 'en': 'Order enquiries'},
    {'de': 'Mehrsprachig', 'it': 'Multilingue', 'en': 'Multilingual'}],
   {'de': 'In Bewegung. Digital stärker.', 'it': 'In movimento. Più forti online.', 'en': 'On the move. Stronger online.'}),
 'lebensmittel': ('handel', {'de': 'LEBENSMITTEL & GENUSS', 'it': 'ALIMENTARI & GUSTO', 'en': 'FOOD & FINE PRODUCE'},
   {'de': 'Herkunft und Qualität zeigen.', 'it': 'Mostrare origine e qualità.', 'en': 'Show origin and quality.'},
   [{'de': 'Produkte stilvoll präsentiert', 'it': 'Prodotti presentati con stile', 'en': 'Products presented in style'},
    {'de': 'Onlineshop (optional)', 'it': 'Negozio online (opzionale)', 'en': 'Online shop (optional)'},
    {'de': 'Herkunft & Geschichte', 'it': 'Origine e storia', 'en': 'Origin & story'},
    {'de': 'Bilder, die Appetit machen', 'it': 'Foto che fanno venire fame', 'en': 'Mouth-watering photos'}],
   {'de': 'Genuss, der online beginnt.', 'it': 'Il gusto che inizia online.', 'en': 'Taste that starts online.'}),
 'shop': ('handel', {'de': 'MODE & EINZELHANDEL', 'it': 'MODA & NEGOZI', 'en': 'FASHION & RETAIL'},
   {'de': 'Ihre Marke emotional erlebbar.', 'it': 'Il suo marchio da vivere.', 'en': 'Your brand, brought to life.'},
   [{'de': 'Produkte modern präsentiert', 'it': 'Prodotti presentati in modo moderno', 'en': 'Products presented in a modern way'},
    {'de': 'Onlineshop möglich', 'it': 'Negozio online possibile', 'en': 'Online shop possible'},
    {'de': 'Lookbooks & Galerien', 'it': 'Lookbook e gallerie', 'en': 'Lookbooks & galleries'},
    {'de': 'Für alle Geräte gebaut', 'it': 'Per tutti i dispositivi', 'en': 'Built for every device'}],
   {'de': 'Stil, der online wirkt.', 'it': 'Stile che funziona online.', 'en': 'Style that works online.'}),
 'bildung': ('kreativ', {'de': 'BILDUNG & COACHING', 'it': 'FORMAZIONE & COACHING', 'en': 'EDUCATION & COACHING'},
   {'de': 'Wissen professionell präsentiert.', 'it': 'Il sapere presentato con cura.', 'en': 'Knowledge, professionally presented.'},
   [{'de': 'Kurse & Termine online', 'it': 'Corsi e date online', 'en': 'Courses & dates online'},
    {'de': 'Anmeldeformulare', 'it': 'Moduli di iscrizione', 'en': 'Registration forms'},
    {'de': 'Mitgliederbereich (optional)', 'it': 'Area riservata (opzionale)', 'en': 'Members’ area (optional)'},
    {'de': 'Referenzen & Stimmen', 'it': 'Referenze e testimonianze', 'en': 'References & testimonials'}],
   {'de': 'Lernen beginnt mit dem ersten Klick.', 'it': 'Imparare inizia con un clic.', 'en': 'Learning starts with one click.'}),
 'foto': ('kreativ', {'de': 'FOTOGRAFEN', 'it': 'FOTOGRAFI', 'en': 'PHOTOGRAPHERS'},
   {'de': 'Ihre Bilder verdienen eine Bühne.', 'it': 'Le sue foto meritano un palco.', 'en': 'Your pictures deserve a stage.'},
   [{'de': 'Portfolio, das wirkt', 'it': 'Portfolio d’impatto', 'en': 'An impressive portfolio'},
    {'de': 'Kundengalerien', 'it': 'Gallerie clienti', 'en': 'Client galleries'},
    {'de': 'Buchungsanfragen online', 'it': 'Richieste di servizio online', 'en': 'Booking requests online'},
    {'de': 'Modernes, kreatives Design', 'it': 'Design moderno e creativo', 'en': 'Modern, creative design'}],
   {'de': 'Jedes Bild erzählt mehr.', 'it': 'Ogni foto racconta di più.', 'en': 'Every picture tells more.'}),
 'events': ('gast', {'de': 'EVENTS & VERANSTALTUNGEN', 'it': 'EVENTI', 'en': 'EVENTS'},
   {'de': 'Atmosphäre, die man spürt.', 'it': 'Un’atmosfera che si sente.', 'en': 'An atmosphere you can feel.'},
   [{'de': 'Eventdetails & Programm', 'it': 'Dettagli e programma', 'en': 'Event details & programme'},
    {'de': 'Tickets & Anmeldung', 'it': 'Biglietti e iscrizioni', 'en': 'Tickets & registration'},
    {'de': 'Bilder & Videos', 'it': 'Foto e video', 'en': 'Photos & videos'},
    {'de': 'Künstler & Partner', 'it': 'Artisti e partner', 'en': 'Artists & partners'}],
   {'de': 'Die Bühne beginnt online.', 'it': 'Il palco inizia online.', 'en': 'The stage starts online.'}),
 'caravan': ('handel', {'de': 'REISEMOBILE & CARAVAN', 'it': 'CAMPER & CARAVAN', 'en': 'MOTORHOMES & CARAVANS'},
   {'de': 'Freiheit digital präsentiert.', 'it': 'La libertà presentata online.', 'en': 'Freedom presented online.'},
   [{'de': 'Fahrzeugpräsentation', 'it': 'Presentazione dei veicoli', 'en': 'Vehicle presentation'},
    {'de': 'Vermietung oder Verkauf', 'it': 'Noleggio o vendita', 'en': 'Rental or sale'},
    {'de': 'Verfügbarkeit online', 'it': 'Disponibilità online', 'en': 'Availability online'},
    {'de': 'Anfrageformular', 'it': 'Modulo di richiesta', 'en': 'Enquiry form'}],
   {'de': 'Die Reise beginnt online.', 'it': 'Il viaggio inizia online.', 'en': 'The journey starts online.'}),
 'reinigung': ('bau', {'de': 'GEBÄUDEREINIGUNG', 'it': 'IMPRESE DI PULIZIA', 'en': 'CLEANING SERVICES'},
   {'de': 'Sauber. Zuverlässig. Professionell.', 'it': 'Puliti, affidabili, professionali.', 'en': 'Clean. Reliable. Professional.'},
   [{'de': 'Leistungen klar aufgezeigt', 'it': 'Servizi chiari', 'en': 'Services clearly shown'},
    {'de': 'Angebotsanfragen online', 'it': 'Richieste di preventivo online', 'en': 'Quote requests online'},
    {'de': 'Referenzen & Einsatzgebiete', 'it': 'Referenze e zone servite', 'en': 'References & service areas'},
    {'de': 'Für alle Geräte gebaut', 'it': 'Per tutti i dispositivi', 'en': 'Built for every device'}],
   {'de': 'Ein glänzender erster Eindruck.', 'it': 'Una prima impressione brillante.', 'en': 'A sparkling first impression.'}),
 'sicherheit': ('handel', {'de': 'SICHERHEIT & ALARMSYSTEME', 'it': 'SICUREZZA & ALLARMI', 'en': 'SECURITY & ALARM SYSTEMS'},
   {'de': 'Seriös und modern präsentiert.', 'it': 'Presentati con serietà e modernità.', 'en': 'Presented seriously and modern.'},
   [{'de': 'Leistungen & Produkte', 'it': 'Servizi e prodotti', 'en': 'Services & products'},
    {'de': 'Referenzen & Projekte', 'it': 'Referenze e progetti', 'en': 'References & projects'},
    {'de': 'Anfrageformular', 'it': 'Modulo di richiesta', 'en': 'Enquiry form'},
    {'de': 'Für alle Geräte gebaut', 'it': 'Per tutti i dispositivi', 'en': 'Built for every device'}],
   {'de': 'Sicherheit, die man sieht.', 'it': 'Sicurezza che si vede.', 'en': 'Security you can see.'}),
 'tierarzt': ('gesundheit', {'de': 'TIERÄRZTE & TIERBEDARF', 'it': 'VETERINARI & PET SHOP', 'en': 'VETS & PET SUPPLIES'},
   {'de': 'Für Tiere und ihre Menschen.', 'it': 'Per gli animali e le loro persone.', 'en': 'For pets and their people.'},
   [{'de': 'Terminanfrage online', 'it': 'Richiesta appuntamento online', 'en': 'Online appointment requests'},
    {'de': 'Leistungen im Überblick', 'it': 'Servizi in sintesi', 'en': 'Services at a glance'},
    {'de': 'Produkte & Shop (optional)', 'it': 'Prodotti e shop (opzionale)', 'en': 'Products & shop (optional)'},
    {'de': 'Team vorgestellt', 'it': 'Team presentato', 'en': 'Team introduced'}],
   {'de': 'Mit Herz für jedes Tier.', 'it': 'Con il cuore per ogni animale.', 'en': 'With heart for every animal.'}),
}
