"""Texte der 51 Branchen-Flyer im Originalstil, DE/IT/EN (04.10.2026).

Inhalt so nah wie möglich an Uwes Original-Flyern, nur die Fehler korrigiert
(„präsenteiren“, „Weoseiten“, „Sinfragen“ …). Italienisch in der Höflichkeitsform (Lei).

Je Flyer:
  f       Stilfamilie a|b|c|d (Collage 1–4)
  g       Gruppe im Dashboard (PartnerFlyer::GRUPPEN)
  titel   {de, it, en}
  sub     Unterzeile (b) oder None
  tags    drei Schlagworte (c, d) oder None
  punkte  [(symbol, {de, it, en})] — „\n“ = zweite, leichtere Zeile (c)
  slogan  Handschrift-Zeile (b, c, d) oder None
  leiste  Symbolleiste unten (c): [(symbol, {de, it, en})]
Symbole: Namen aus lucide-static (ISC-Lizenz).
"""

def d(de, it, en):
    return {'de': de, 'it': it, 'en': en}

FEST = {
    'fuer': d('WEBSITES FÜR', 'SITI WEB PER', 'WEBSITES FOR'),
    'cta': d('Jetzt beraten lassen!', 'Richieda una consulenza!', 'Get advice now!'),
    'unter': d('Webdesign · Logo Design · Branding', 'Webdesign · Logo Design · Branding', 'Web design · Logo design · Branding'),
}

F = {
 # ---------------------------------------------------------------- Stil A (Collage 1, 21 Stück)
 'a-autohaus': {'f': 'a', 'g': 'handel', 'titel': d('AUTOHÄUSER', 'CONCESSIONARI AUTO', 'CAR DEALERS'),
   'punkte': [('car', d('3D-Fahrzeugpräsentation', 'Presentazione veicoli in 3D', '3D vehicle presentation')),
              ('monitor-play', d('Virtuelle Showrooms', 'Showroom virtuali', 'Virtual showrooms')),
              ('message-square', d('Mehr Anfragen', 'Più richieste', 'More enquiries')),
              ('badge-check', d('Verkaufsstarkes Design', 'Design che vende', 'Design that sells'))]},
 'a-restaurant': {'f': 'a', 'g': 'gast', 'titel': d('RESTAURANTS\nHOTELS & GASTRONOMIE', 'RISTORANTI\nHOTEL & GASTRONOMIA', 'RESTAURANTS\nHOTELS & HOSPITALITY'),
   'punkte': [('calendar-check', d('Online-Reservierung', 'Prenotazione online', 'Online reservations')),
              ('utensils', d('Digitale Speisekarten', 'Menù digitali', 'Digital menus')),
              ('rotate-3d', d('Stimmungsvolle 3D-Präsentation', 'Presentazione 3D d’atmosfera', 'Atmospheric 3D presentation')),
              ('users', d('Mehr Gäste', 'Più ospiti', 'More guests'))]},
 'a-hotel': {'f': 'a', 'g': 'gast', 'titel': d('HOTELS & TOURISMUS', 'HOTEL & TURISMO', 'HOTELS & TOURISM'),
   'punkte': [('rotate-3d', d('Virtuelle 360°-Touren', 'Tour virtuali a 360°', 'Virtual 360° tours')),
              ('calendar-check', d('Online-Buchungssystem', 'Sistema di prenotazione online', 'Online booking system')),
              ('sparkles', d('Atemberaubende Präsentation', 'Presentazione mozzafiato', 'Stunning presentation')),
              ('bed-double', d('Mehr direkte Buchungen', 'Più prenotazioni dirette', 'More direct bookings'))]},
 'a-immobilien': {'f': 'a', 'g': 'handel', 'titel': d('IMMOBILIEN', 'IMMOBILIARE', 'REAL ESTATE'),
   'punkte': [('rotate-3d', d('3D-Objektpräsentationen', 'Presentazioni 3D degli immobili', '3D property presentations')),
              ('eye', d('Virtuelle Besichtigungen', 'Visite virtuali', 'Virtual viewings')),
              ('message-square', d('Mehr qualifizierte Anfragen', 'Più richieste qualificate', 'More qualified enquiries')),
              ('file-text', d('Professionelles Exposé-Design', 'Schede immobili professionali', 'Professional brochure design'))]},
 'a-handwerk': {'f': 'a', 'g': 'bau', 'titel': d('HANDWERK & BAU', 'ARTIGIANI & EDILIZIA', 'TRADES & CONSTRUCTION'),
   'punkte': [('briefcase', d('Moderne Firmenwebsites', 'Siti aziendali moderni', 'Modern company websites')),
              ('images', d('Projektgalerie & Referenzen', 'Galleria progetti e referenze', 'Project gallery & references')),
              ('message-square', d('Mehr Kundenanfragen', 'Più richieste dai clienti', 'More customer enquiries')),
              ('shield-check', d('Starkes & seriöses Design', 'Design forte e serio', 'Strong, trustworthy design'))]},
 'a-arztpraxis': {'f': 'a', 'g': 'gesundheit', 'hell': True, 'titel': d('ÄRZTE & PRAXEN', 'MEDICI & STUDI', 'DOCTORS & PRACTICES'),
   'punkte': [('calendar-check', d('Online-Terminvereinbarung', 'Appuntamenti online', 'Online appointments')),
              ('heart-handshake', d('Vertrauen & Kompetenz', 'Fiducia e competenza', 'Trust & expertise')),
              ('list-checks', d('Übersichtliche Leistungen', 'Prestazioni chiare', 'Clear list of services')),
              ('shield-check', d('Datenschutz & Sicherheit', 'Privacy e sicurezza', 'Privacy & security'))]},
 'a-beauty': {'f': 'a', 'g': 'gesundheit', 'titel': d('BEAUTY & WELLNESS', 'BELLEZZA & BENESSERE', 'BEAUTY & WELLNESS'),
   'punkte': [('calendar-check', d('Terminbuchung online', 'Prenotazione online', 'Online booking')),
              ('sparkles', d('Elegantes Design', 'Design elegante', 'Elegant design')),
              ('list-checks', d('Behandlungsübersicht', 'Trattamenti in sintesi', 'Treatments at a glance')),
              ('heart', d('Mehr Neukunden', 'Più nuovi clienti', 'More new clients'))]},
 'a-fitness': {'f': 'a', 'g': 'gesundheit', 'titel': d('FITNESSSTUDIOS', 'PALESTRE', 'GYMS & FITNESS STUDIOS'),
   'punkte': [('users', d('Mitglieder gewinnen', 'Conquistare nuovi iscritti', 'Win new members')),
              ('calendar-days', d('Kurspläne online', 'Orari dei corsi online', 'Class schedules online')),
              ('monitor-smartphone', d('Moderne Präsentation', 'Presentazione moderna', 'Modern presentation')),
              ('dumbbell', d('Motivierendes Design', 'Design motivante', 'Motivating design'))]},
 'a-kanzlei': {'f': 'a', 'g': 'beratung', 'titel': d('KANZLEIEN', 'STUDI LEGALI', 'LAW FIRMS'),
   'punkte': [('shield-check', d('Seriöses & diskretes Design', 'Design serio e discreto', 'Serious, discreet design')),
              ('users', d('Mandanten gewinnen', 'Conquistare clienti', 'Win new clients')),
              ('list-checks', d('Leistungsübersicht', 'Panoramica dei servizi', 'Overview of services')),
              ('scale', d('Vertrauen & Kompetenz', 'Fiducia e competenza', 'Trust & expertise'))]},
 'a-steuerberater': {'f': 'a', 'g': 'beratung', 'titel': d('STEUERBERATER', 'COMMERCIALISTI', 'TAX ADVISERS'),
   'punkte': [('briefcase', d('Professionelles Auftreten', 'Immagine professionale', 'Professional appearance')),
              ('list-checks', d('Leistungen klar präsentieren', 'Servizi presentati con chiarezza', 'Present services clearly')),
              ('mail', d('Digitale Mandantenanfragen', 'Richieste dei clienti online', 'Digital client enquiries')),
              ('shield-check', d('Modern & vertrauenswürdig', 'Moderno e affidabile', 'Modern & trustworthy'))]},
 'a-logistik': {'f': 'a', 'g': 'handel', 'titel': d('LOGISTIK & TRANSPORT', 'LOGISTICA & TRASPORTI', 'LOGISTICS & TRANSPORT'),
   'punkte': [('building-2', d('Unternehmenspräsentation', 'Presentazione aziendale', 'Company presentation')),
              ('truck', d('Leistungen & Fuhrpark', 'Servizi e parco mezzi', 'Services & fleet')),
              ('message-square', d('Anfragen für Aufträge', 'Richieste di trasporto', 'Job enquiries')),
              ('globe', d('Internationale Ausrichtung', 'Respiro internazionale', 'International reach'))]},
 'a-solar': {'f': 'a', 'g': 'bau', 'titel': d('SOLAR & ENERGIE', 'SOLARE & ENERGIA', 'SOLAR & ENERGY'),
   'punkte': [('list-checks', d('Leistungen übersichtlich', 'Servizi chiari', 'Clear list of services')),
              ('badge-euro', d('Förderungen & Vorteile', 'Incentivi e vantaggi', 'Subsidies & benefits')),
              ('images', d('Projekte & Referenzen', 'Progetti e referenze', 'Projects & references')),
              ('message-square', d('Mehr Kundenanfragen', 'Più richieste dai clienti', 'More customer enquiries'))]},
 'a-lebensmittel': {'f': 'a', 'g': 'handel', 'titel': d('LEBENSMITTEL & GENUSS', 'ALIMENTARI & GUSTO', 'FOOD & FINE PRODUCE'),
   'punkte': [('sparkles', d('Produkte stilvoll präsentieren', 'Prodotti presentati con stile', 'Stylish product presentation')),
              ('shopping-cart', d('Onlineshop (optional)', 'Negozio online (opzionale)', 'Online shop (optional)')),
              ('leaf', d('Herkunft & Qualität zeigen', 'Origine e qualità in primo piano', 'Show origin & quality')),
              ('trending-up', d('Mehr Reichweite & Verkäufe', 'Più visibilità e vendite', 'More reach & sales'))]},
 'a-mode': {'f': 'a', 'g': 'handel', 'titel': d('MODE & EINZELHANDEL', 'MODA & NEGOZI', 'FASHION & RETAIL'),
   'punkte': [('shirt', d('Produkte modern präsentieren', 'Prodotti presentati in modo moderno', 'Modern product presentation')),
              ('shopping-bag', d('Onlineshop möglich', 'Negozio online possibile', 'Online shop possible')),
              ('heart', d('Marke emotional erlebbar', 'Il marchio da vivere', 'A brand people can feel')),
              ('trending-up', d('Mehr Verkäufe', 'Più vendite', 'More sales'))]},
 'a-bildung': {'f': 'a', 'g': 'kreativ', 'titel': d('BILDUNG & COACHING', 'FORMAZIONE & COACHING', 'EDUCATION & COACHING'),
   'punkte': [('calendar-days', d('Kurse & Termine online', 'Corsi e date online', 'Courses & dates online')),
              ('graduation-cap', d('Wissen professionell präsentieren', 'Competenze presentate con professionalità', 'Present knowledge professionally')),
              ('lock', d('Mitgliederbereich (optional)', 'Area riservata (opzionale)', 'Members’ area (optional)')),
              ('users', d('Mehr Teilnehmer', 'Più partecipanti', 'More participants'))]},
 'a-foto': {'f': 'a', 'g': 'kreativ', 'titel': d('FOTOGRAFEN', 'FOTOGRAFI', 'PHOTOGRAPHERS'),
   'punkte': [('camera', d('Portfolio beeindruckend zeigen', 'Un portfolio che colpisce', 'Show an impressive portfolio')),
              ('images', d('Kundengalerien', 'Gallerie per i clienti', 'Client galleries')),
              ('calendar-check', d('Buchungsanfragen online', 'Richieste di prenotazione online', 'Online booking requests')),
              ('sparkles', d('Modernes & kreatives Design', 'Design moderno e creativo', 'Modern, creative design'))]},
 'a-events': {'f': 'a', 'g': 'gast', 'titel': d('EVENTS & VERANSTALTUNGEN', 'EVENTI & MANIFESTAZIONI', 'EVENTS & SHOWS'),
   'punkte': [('ticket', d('Eventdetails & Tickets', 'Dettagli e biglietti', 'Event details & tickets')),
              ('sparkles', d('Atemberaubende Visuals', 'Immagini mozzafiato', 'Stunning visuals')),
              ('music', d('Künstler & Programm', 'Artisti e programma', 'Artists & line-up')),
              ('trending-up', d('Mehr Ticketverkäufe', 'Più biglietti venduti', 'More ticket sales'))]},
 'a-caravan': {'f': 'a', 'g': 'handel', 'titel': d('REISEMOBILE & CARAVAN', 'CAMPER & CARAVAN', 'MOTORHOMES & CARAVANS'),
   'punkte': [('caravan', d('Fahrzeugpräsentation', 'Presentazione dei veicoli', 'Vehicle presentation')),
              ('key-round', d('Vermietung oder Verkauf', 'Noleggio o vendita', 'Rental or sale')),
              ('calendar-days', d('Verfügbarkeiten online', 'Disponibilità online', 'Availability online')),
              ('message-square', d('Mehr Anfragen', 'Più richieste', 'More enquiries'))]},
 'a-reinigung': {'f': 'a', 'g': 'bau', 'titel': d('GEBÄUDEREINIGUNG', 'IMPRESE DI PULIZIA', 'CLEANING SERVICES'),
   'punkte': [('list-checks', d('Leistungen klar aufzeigen', 'Servizi spiegati con chiarezza', 'Show services clearly')),
              ('mail', d('Angebotsanfragen online', 'Richieste di preventivo online', 'Online quote requests')),
              ('shield-check', d('Vertrauen & Professionalität', 'Fiducia e professionalità', 'Trust & professionalism')),
              ('map-pin', d('Regional mehr Kunden', 'Più clienti in zona', 'More local customers'))]},
 'a-sicherheit': {'f': 'a', 'g': 'bau', 'titel': d('SICHERHEIT & ALARMSYSTEME', 'SICUREZZA & ALLARMI', 'SECURITY & ALARM SYSTEMS'),
   'punkte': [('shield-check', d('Leistungen & Produkte', 'Servizi e prodotti', 'Services & products')),
              ('images', d('Referenzen & Projekte', 'Referenze e progetti', 'References & projects')),
              ('message-square', d('Mehr Kundenanfragen', 'Più richieste dai clienti', 'More customer enquiries')),
              ('badge-check', d('Seriöses & modernes Design', 'Design serio e moderno', 'Serious, modern design'))]},
 'a-tierarzt': {'f': 'a', 'g': 'gesundheit', 'titel': d('TIERÄRZTE & TIERBEDARF', 'VETERINARI & PET SHOP', 'VETS & PET SUPPLIES'),
   'punkte': [('calendar-check', d('Terminbuchung online', 'Prenotazione online', 'Online booking')),
              ('list-checks', d('Leistungen übersichtlich', 'Servizi chiari', 'Clear list of services')),
              ('shopping-bag', d('Produkte & Shop (optional)', 'Prodotti e shop (opzionale)', 'Products & shop (optional)')),
              ('paw-print', d('Mehr Kunden & Tierfreunde', 'Più clienti e amici degli animali', 'More customers & pet lovers'))]},
 # ---------------------------------------------------------------- Stil B (Collage 2, 10 Stück)
 'b-handwerk': {'f': 'b', 'g': 'bau', 'titel': d('BAU & HANDWERK', 'EDILIZIA & ARTIGIANI', 'CONSTRUCTION & TRADES'),
   'sub': d('Ihre Projekte digital perfekt präsentiert.', 'I suoi progetti, presentati alla perfezione.', 'Your projects, perfectly presented online.'),
   'punkte': [('images', d('Projekte & Referenzen', 'Progetti e referenze', 'Projects & references')),
              ('list-checks', d('Leistungen übersichtlich', 'Servizi chiari', 'Clear list of services')),
              ('clipboard-list', d('Anfrageformular', 'Modulo di richiesta', 'Enquiry form')),
              ('map-pin', d('Lokal gefunden bei Google', 'Trovati in zona su Google', 'Found locally on Google'))],
   'slogan': d('Starke Arbeit.\nStarke Website.', 'Lavoro solido.\nSito solido.', 'Great work.\nGreat website.')},
 'b-arztpraxis': {'f': 'b', 'g': 'gesundheit', 'hell': True, 'titel': d('ÄRZTE & PRAXEN', 'MEDICI & STUDI', 'DOCTORS & PRACTICES'),
   'sub': d('Vertrauen. Kompetenz. Modern präsentiert.', 'Fiducia. Competenza. Presentate in modo moderno.', 'Trust. Expertise. Presented the modern way.'),
   'punkte': [('calendar-check', d('Terminvereinbarung online', 'Appuntamenti online', 'Online appointments')),
              ('list-checks', d('Leistungen übersichtlich', 'Prestazioni chiare', 'Clear list of services')),
              ('heart-handshake', d('Vertrauen durch professionelles Design', 'Fiducia grazie a un design professionale', 'Trust through professional design')),
              ('map-pin', d('Optimiert für die lokale Suche', 'Ottimizzato per la ricerca locale', 'Optimised for local search'))],
   'slogan': d('Mehr Zeit für Ihre Patienten.\nWir kümmern uns\num Ihre Website.', 'Più tempo per i pazienti.\nAl suo sito\npensiamo noi.', 'More time for your patients.\nWe take care\nof your website.')},
 'b-immobilien': {'f': 'b', 'g': 'handel', 'titel': d('IMMOBILIEN', 'IMMOBILIARE', 'REAL ESTATE'),
   'sub': d('Exposés, die begeistern.', 'Schede immobili che conquistano.', 'Listings that impress.'),
   'punkte': [('house', d('Hochwertige Objektpräsentation', 'Presentazione curata degli immobili', 'High-quality property presentation')),
              ('rotate-3d', d('Virtuelle 3D-Rundgänge', 'Tour virtuali in 3D', 'Virtual 3D tours')),
              ('clipboard-list', d('Kontakt- und Anfrageformulare', 'Moduli di contatto e richiesta', 'Contact and enquiry forms')),
              ('users', d('Optimiert für Käufer & Mieter', 'Pensato per acquirenti e inquilini', 'Built for buyers & tenants'))],
   'slogan': d('Immobilien\ndigital erleben.', 'Vivere gli immobili\nonline.', 'Experience\nproperties online.')},
 'b-beauty': {'f': 'b', 'g': 'gesundheit', 'titel': d('BEAUTY & WELLNESS', 'BELLEZZA & BENESSERE', 'BEAUTY & WELLNESS'),
   'sub': d('Schönheit digital in Szene gesetzt.', 'La bellezza messa in scena online.', 'Beauty, beautifully presented online.'),
   'punkte': [('sparkles', d('Elegantes Design', 'Design elegante', 'Elegant design')),
              ('calendar-check', d('Terminbuchung online', 'Prenotazione online', 'Online booking')),
              ('list-checks', d('Behandlungsübersicht', 'Trattamenti in sintesi', 'Treatments at a glance')),
              ('camera', d('Professionelle Bilder & Videos', 'Foto e video professionali', 'Professional photos & videos')),
              ('map-pin', d('Mehr Kunden durch Google', 'Più clienti grazie a Google', 'More clients via Google'))],
   'slogan': d('Entspannung\nbeginnt online.', 'Il relax\ninizia online.', 'Relaxation\nstarts online.')},
 'b-restaurant': {'f': 'b', 'g': 'gast', 'titel': d('RESTAURANTS', 'RISTORANTI', 'RESTAURANTS'),
   'sub': d('Genuss digital erleben.', 'Il gusto, anche online.', 'Enjoy great food – online too.'),
   'punkte': [('utensils', d('Speisekarten online', 'Menù online', 'Menus online')),
              ('calendar-check', d('Reservierungssystem', 'Sistema di prenotazione', 'Reservation system')),
              ('camera', d('Bilder, die Appetit machen', 'Foto che fanno venire fame', 'Mouth-watering photos')),
              ('clipboard-list', d('Events & Neuigkeiten', 'Eventi e novità', 'Events & news')),
              ('map-pin', d('Mehr Gäste durch Google', 'Più ospiti grazie a Google', 'More guests via Google'))],
   'slogan': d('Mehr als eine Speisekarte.\nEin Erlebnis.', 'Più di un menù.\nUn’esperienza.', 'More than a menu.\nAn experience.')},
 'b-hotel': {'f': 'b', 'g': 'gast', 'titel': d('HOTELS & FERIENWOHNUNGEN', 'HOTEL & CASE VACANZA', 'HOTELS & HOLIDAY HOMES'),
   'sub': d('Gäste begeistern. Direktbuchungen steigern.', 'Ospiti entusiasti. Più prenotazioni dirette.', 'Delight guests. Boost direct bookings.'),
   'punkte': [('bed-double', d('Zimmer & Preise', 'Camere e prezzi', 'Rooms & rates')),
              ('calendar-check', d('Buchungssystem', 'Sistema di prenotazione', 'Booking system')),
              ('rotate-3d', d('Galerien & 3D-Rundgänge', 'Gallerie e tour 3D', 'Galleries & 3D tours')),
              ('map-pin', d('Standort & Umgebung', 'Posizione e dintorni', 'Location & surroundings')),
              ('search', d('Mehr Sichtbarkeit bei Google', 'Più visibilità su Google', 'More visibility on Google'))],
   'slogan': d('Urlaub\nbeginnt online.', 'La vacanza\ninizia online.', 'Holidays\nstart online.')},
 'b-fitness': {'f': 'b', 'g': 'gesundheit', 'titel': d('FITNESS & SPORT', 'FITNESS & SPORT', 'FITNESS & SPORT'),
   'sub': d('Motivation digital erleben.', 'Motivazione, anche online.', 'Motivation, online too.'),
   'punkte': [('calendar-days', d('Kurspläne & Trainer', 'Corsi e istruttori', 'Class schedules & trainers')),
              ('id-card', d('Mitgliedschaften online', 'Abbonamenti online', 'Memberships online')),
              ('video', d('Video & Trainingsbereiche', 'Video e aree di allenamento', 'Video & training areas')),
              ('clipboard-list', d('Anmeldung & Probetraining', 'Iscrizione e prova gratuita', 'Sign-up & trial session')),
              ('map-pin', d('Mehr Mitglieder durch Google', 'Più iscritti grazie a Google', 'More members via Google'))],
   'slogan': d('Mehr als Training.\nEine Community.', 'Più di un allenamento.\nUna community.', 'More than training.\nA community.')},
 'b-tourismus': {'f': 'b', 'g': 'gast', 'titel': d('REISEN & TOURISMUS', 'VIAGGI & TURISMO', 'TRAVEL & TOURISM'),
   'sub': d('Einzigartige Erlebnisse digital präsentiert.', 'Esperienze uniche presentate online.', 'Unique experiences presented online.'),
   'punkte': [('map', d('Reiseangebote & Touren', 'Offerte di viaggio e tour', 'Trips & tours')),
              ('camera', d('Bilder & Videos', 'Foto e video', 'Photos & videos')),
              ('calendar-check', d('Buchungssystem', 'Sistema di prenotazione', 'Booking system')),
              ('languages', d('Mehrsprachig', 'Multilingue', 'Multilingual')),
              ('map-pin', d('Mehr Buchungen durch Google', 'Più prenotazioni grazie a Google', 'More bookings via Google'))],
   'slogan': d('Die Welt\nnur einen Klick\nentfernt.', 'Il mondo\na un clic\ndi distanza.', 'The world\njust one click\naway.')},
 'b-kanzlei': {'f': 'b', 'g': 'beratung', 'titel': d('RECHTSANWÄLTE & KANZLEIEN', 'AVVOCATI & STUDI LEGALI', 'LAWYERS & LAW FIRMS'),
   'sub': d('Seriös. Kompetent. Vertrauenswürdig.', 'Seri. Competenti. Affidabili.', 'Serious. Competent. Trustworthy.'),
   'punkte': [('list-checks', d('Leistungen übersichtlich', 'Servizi chiari', 'Clear list of services')),
              ('users', d('Team & Fachgebiete', 'Team e aree di competenza', 'Team & practice areas')),
              ('lock', d('Mandantenbereich', 'Area clienti', 'Client area')),
              ('newspaper', d('Aktuelle Rechtsthemen', 'Temi giuridici d’attualità', 'Current legal topics')),
              ('map-pin', d('Optimiert für die lokale Suche', 'Ottimizzato per la ricerca locale', 'Optimised for local search'))],
   'slogan': d('Vertrauen\nbeginnt online.', 'La fiducia\ninizia online.', 'Trust\nstarts online.')},
 'b-solar': {'f': 'b', 'g': 'bau', 'titel': d('SOLAR & ENERGIE', 'SOLARE & ENERGIA', 'SOLAR & ENERGY'),
   'sub': d('Nachhaltige Lösungen digital stark präsentiert.', 'Soluzioni sostenibili, presentate al meglio.', 'Sustainable solutions, strongly presented.'),
   'punkte': [('sun', d('Leistungen & Vorteile', 'Servizi e vantaggi', 'Services & benefits')),
              ('images', d('Projekte & Referenzen', 'Progetti e referenze', 'Projects & references')),
              ('badge-euro', d('Fördermöglichkeiten', 'Incentivi possibili', 'Funding options')),
              ('clipboard-list', d('Anfrageformular', 'Modulo di richiesta', 'Enquiry form')),
              ('map-pin', d('Mehr Kunden durch Google', 'Più clienti grazie a Google', 'More customers via Google'))],
   'slogan': d('Heute in eine\nbessere Zukunft\ninvestieren.', 'Investire oggi\nin un futuro\nmigliore.', 'Invest today\nin a better\nfuture.')},
 # ---------------------------------------------------------------- Stil C (Collage 3, 10 Stück)
 'c-handwerk': {'f': 'c', 'g': 'bau', 'titel': d('HANDWERK', 'ARTIGIANI', 'TRADES'),
   'tags': [d('REGIONAL', 'LOCALE', 'LOCAL'), d('MODERN', 'MODERNO', 'MODERN'), d('VERTRAUENSSTARK', 'AFFIDABILE', 'TRUSTED')],
   'punkte': [('hammer', d('Mehr Aufträge\ndurch professionelle Online-Präsenz', 'Più lavori\ngrazie a una presenza online professionale', 'More jobs\nthrough a professional online presence')),
              ('list-checks', d('Leistungen klar\nund überzeugend darstellen', 'Servizi presentati\nin modo chiaro e convincente', 'Present services\nclearly and convincingly')),
              ('camera', d('Referenzen & Projekte\noptimal präsentieren', 'Referenze e progetti\npresentati al meglio', 'References & projects\nshown at their best')),
              ('smartphone', d('Für alle Geräte optimiert', 'Ottimizzato per ogni dispositivo', 'Optimised for every device'))],
   'slogan': d('Starke Handwerker.\nStarke Websites.', 'Artigiani forti.\nSiti forti.', 'Strong trades.\nStrong websites.'),
   'leiste': [('monitor', d('WEBDESIGN', 'WEBDESIGN', 'WEB DESIGN')), ('box', d('3D & VIRTUELL', '3D E VIRTUALE', '3D & VIRTUAL')),
              ('search', d('SEO OPTIMIERT', 'SEO OTTIMIZZATO', 'SEO OPTIMISED')), ('pen-tool', d('INDIVIDUELL', 'SU MISURA', 'TAILORED'))]},
 'c-immobilien': {'f': 'c', 'g': 'handel', 'titel': d('IMMOBILIEN', 'IMMOBILIARE', 'REAL ESTATE'),
   'tags': [d('MODERN', 'MODERNO', 'MODERN'), d('EXKLUSIV', 'ESCLUSIVO', 'EXCLUSIVE'), d('VERKAUFSSTARK', 'CHE VENDE', 'SELLS WELL')],
   'punkte': [('house', d('Objekte perfekt\npräsentieren', 'Immobili presentati\nalla perfezione', 'Present properties\nperfectly')),
              ('rotate-3d', d('Virtuelle 3D-Rundgänge\nund interaktive Exposés', 'Tour virtuali in 3D\ne schede interattive', 'Virtual 3D tours\nand interactive listings')),
              ('message-square', d('Mehr Anfragen\nund qualifizierte Kunden', 'Più richieste\ne clienti qualificati', 'More enquiries\nand qualified buyers')),
              ('smartphone', d('Einfache Verwaltung', 'Gestione semplice', 'Easy to manage'))],
   'slogan': d('Immobilien\ndigital erleben.', 'Vivere gli immobili\nonline.', 'Experience\nproperties online.'),
   'leiste': [('box', d('3D-TOUREN', 'TOUR 3D', '3D TOURS')), ('file-text', d('EXPOSÉS', 'SCHEDE', 'LISTINGS')),
              ('search', d('SEO OPTIMIERT', 'SEO OTTIMIZZATO', 'SEO OPTIMISED')), ('monitor-smartphone', d('RESPONSIVE', 'RESPONSIVE', 'RESPONSIVE'))]},
 'c-arztpraxis': {'f': 'c', 'g': 'gesundheit', 'hell': True, 'titel': d('ÄRZTE & PRAXEN', 'MEDICI & STUDI', 'DOCTORS & PRACTICES'),
   'tags': [d('MODERN', 'MODERNO', 'MODERN'), d('ÜBERSICHTLICH', 'CHIARO', 'CLEAR'), d('PATIENTENFREUNDLICH', 'VICINO AI PAZIENTI', 'PATIENT-FRIENDLY')],
   'punkte': [('calendar-check', d('Online-Terminbuchung\neinfach integriert', 'Prenotazione online\nintegrata con semplicità', 'Online booking\nsimply built in')),
              ('list-checks', d('Leistungen klar\nund verständlich darstellen', 'Prestazioni spiegate\nin modo chiaro', 'Explain services\nclearly and simply')),
              ('heart-handshake', d('Vertrauensvolle Darstellung\nIhrer Praxis', 'Il suo studio\npresentato con fiducia', 'A trustworthy picture\nof your practice')),
              ('smartphone', d('Für alle Geräte optimiert', 'Ottimizzato per ogni dispositivo', 'Optimised for every device'))],
   'slogan': d('Vertrauen\nbeginnt online.', 'La fiducia\ninizia online.', 'Trust\nstarts online.'),
   'leiste': [('calendar-days', d('TERMINBUCHUNG', 'PRENOTAZIONI', 'BOOKING')), ('shield-check', d('DATENSCHUTZ', 'PRIVACY', 'PRIVACY')),
              ('search', d('SEO OPTIMIERT', 'SEO OTTIMIZZATO', 'SEO OPTIMISED')), ('pen-tool', d('INDIVIDUELLES DESIGN', 'DESIGN SU MISURA', 'CUSTOM DESIGN'))]},
 'c-beauty': {'f': 'c', 'g': 'gesundheit', 'titel': d('BEAUTY & KOSMETIK', 'BELLEZZA & ESTETICA', 'BEAUTY & COSMETICS'),
   'tags': [d('ELEGANT', 'ELEGANTE', 'ELEGANT'), d('EMOTIONAL', 'EMOZIONALE', 'EMOTIONAL'), d('KUNDENORIENTIERT', 'SU MISURA DEL CLIENTE', 'CLIENT-FOCUSED')],
   'punkte': [('sparkles', d('Behandlungen stilvoll\npräsentieren', 'Trattamenti presentati\ncon stile', 'Present treatments\nwith style')),
              ('calendar-check', d('Online-Terminbuchung', 'Prenotazione online', 'Online booking')),
              ('camera', d('Bilder & Videos in Szene setzen', 'Foto e video in primo piano', 'Photos & videos in the spotlight')),
              ('users', d('Mehr Neukunden\nund Stammkunden', 'Più nuovi clienti\ne clienti fedeli', 'More new\nand regular clients'))],
   'slogan': d('Schönheit\ndigital\ninszeniert.', 'Bellezza\nmessa in scena\nonline.', 'Beauty,\nstaged\nonline.'),
   'leiste': [('images', d('GALERIEN', 'GALLERIE', 'GALLERIES')), ('calendar-days', d('TERMINBUCHUNG', 'PRENOTAZIONI', 'BOOKING')),
              ('search', d('SEO OPTIMIERT', 'SEO OTTIMIZZATO', 'SEO OPTIMISED')), ('share-2', d('SOCIAL MEDIA', 'SOCIAL MEDIA', 'SOCIAL MEDIA'))]},
 'c-fitness': {'f': 'c', 'g': 'gesundheit', 'titel': d('FITNESS & GESUNDHEIT', 'FITNESS & SALUTE', 'FITNESS & HEALTH'),
   'tags': [d('MODERN', 'MODERNO', 'MODERN'), d('MOTIVIEREND', 'MOTIVANTE', 'MOTIVATING'), d('ERFOLGSORIENTIERT', 'ORIENTATO AI RISULTATI', 'RESULTS-DRIVEN')],
   'punkte': [('dumbbell', d('Kurse & Angebote\nübersichtlich präsentieren', 'Corsi e offerte\npresentati con chiarezza', 'Classes & offers\nclearly presented')),
              ('calendar-check', d('Online-Anmeldung\nfür Kurse und Probetraining', 'Iscrizione online\na corsi e prove', 'Online sign-up\nfor classes and trials')),
              ('lock', d('Mitgliederbereich integrierbar', 'Area iscritti integrabile', 'Members’ area available')),
              ('search', d('Mehr Sichtbarkeit\nund neue Mitglieder', 'Più visibilità\ne nuovi iscritti', 'More visibility\nand new members'))],
   'slogan': d('Fitness\ndigital\nstärker.', 'Fitness,\nonline\npiù forte.', 'Fitness,\nstronger\nonline.'),
   'leiste': [('calendar-days', d('KURSPLAN', 'ORARI CORSI', 'TIMETABLE')), ('lock', d('MITGLIEDERBEREICH', 'AREA ISCRITTI', 'MEMBERS’ AREA')),
              ('search', d('SEO OPTIMIERT', 'SEO OTTIMIZZATO', 'SEO OPTIMISED')), ('monitor-smartphone', d('RESPONSIVE', 'RESPONSIVE', 'RESPONSIVE'))]},
 'c-gastro': {'f': 'c', 'g': 'gast', 'titel': d('GASTRONOMIE & HOTELS', 'RISTORAZIONE & HOTEL', 'RESTAURANTS & HOTELS'),
   'tags': [d('APPETITLICH', 'INVITANTE', 'APPETISING'), d('EMOTIONAL', 'EMOZIONALE', 'EMOTIONAL'), d('BUCHUNGSSTARK', 'PIÙ PRENOTAZIONI', 'BOOKS WELL')],
   'punkte': [('utensils', d('Speisekarten digital präsentieren', 'Menù presentati online', 'Menus presented online')),
              ('calendar-check', d('Online-Reservierungen', 'Prenotazioni online', 'Online reservations')),
              ('camera', d('Bilder & Videos, die begeistern', 'Foto e video che conquistano', 'Photos & videos that inspire')),
              ('trending-up', d('Mehr Gäste und höhere Umsätze', 'Più ospiti e più fatturato', 'More guests and higher turnover'))],
   'slogan': d('Genuss\ndigital\nerleben.', 'Il gusto,\nanche\nonline.', 'Taste,\nonline\ntoo.'),
   'leiste': [('utensils', d('SPEISEKARTEN', 'MENÙ', 'MENUS')), ('calendar-days', d('RESERVIERUNG', 'PRENOTAZIONI', 'RESERVATIONS')),
              ('images', d('GALERIEN', 'GALLERIE', 'GALLERIES')), ('search', d('SEO OPTIMIERT', 'SEO OTTIMIZZATO', 'SEO OPTIMISED'))]},
 'c-tourismus': {'f': 'c', 'g': 'gast', 'titel': d('REISEN & TOURISMUS', 'VIAGGI & TURISMO', 'TRAVEL & TOURISM'),
   'tags': [d('INSPIRIEREND', 'CHE ISPIRA', 'INSPIRING'), d('EMOTIONAL', 'EMOZIONALE', 'EMOTIONAL'), d('BUCHUNGSSTARK', 'PIÙ PRENOTAZIONI', 'BOOKS WELL')],
   'punkte': [('map', d('Angebote & Reisen\nattraktiv präsentieren', 'Offerte e viaggi\npresentati al meglio', 'Offers & trips\nattractively presented')),
              ('calendar-check', d('Buchungsanfragen integrieren', 'Richieste di prenotazione integrate', 'Booking requests built in')),
              ('rotate-3d', d('Bilder, Videos und 3D-Erlebnisse', 'Foto, video ed esperienze 3D', 'Photos, videos and 3D experiences')),
              ('users', d('Mehr Kunden und Sichtbarkeit', 'Più clienti e visibilità', 'More customers and visibility'))],
   'slogan': d('Reisen\ndigital\ninspiriert.', 'Viaggi\nche ispirano\nonline.', 'Travel,\ninspired\nonline.'),
   'leiste': [('map', d('REISEANGEBOTE', 'OFFERTE', 'TRIPS')), ('images', d('GALERIEN', 'GALLERIE', 'GALLERIES')),
              ('message-square', d('ANFRAGEN', 'RICHIESTE', 'ENQUIRIES')), ('search', d('SEO OPTIMIERT', 'SEO OTTIMIZZATO', 'SEO OPTIMISED'))]},
 'c-kanzlei': {'f': 'c', 'g': 'beratung', 'titel': d('KANZLEIEN', 'STUDI LEGALI', 'LAW FIRMS'),
   'tags': [d('SERIÖS', 'SERIO', 'SERIOUS'), d('MODERN', 'MODERNO', 'MODERN'), d('VERTRAUENSVOLL', 'AFFIDABILE', 'TRUSTWORTHY')],
   'punkte': [('user-check', d('Leistungen klar darstellen', 'Servizi presentati con chiarezza', 'Present your services clearly')),
              ('users', d('Kompetenz und Vertrauen stärken', 'Rafforzare competenza e fiducia', 'Build expertise and trust')),
              ('newspaper', d('Fachartikel und aktuelle Themen', 'Articoli e temi d’attualità', 'Articles and current topics')),
              ('clipboard-list', d('Mehr Mandanten und Anfragen', 'Più clienti e richieste', 'More clients and enquiries'))],
   'slogan': d('Kompetenz,\ndie Vertrauen\nschafft.', 'Competenza\nche crea\nfiducia.', 'Expertise\nthat builds\ntrust.'),
   'leiste': [('newspaper', d('FACHARTIKEL', 'ARTICOLI', 'ARTICLES')), ('contact', d('KONTAKT', 'CONTATTO', 'CONTACT')),
              ('search', d('SEO OPTIMIERT', 'SEO OTTIMIZZATO', 'SEO OPTIMISED')), ('monitor-smartphone', d('RESPONSIVE', 'RESPONSIVE', 'RESPONSIVE'))]},
 'c-industrie': {'f': 'c', 'g': 'handel', 'titel': d('INDUSTRIE & MASCHINENBAU', 'INDUSTRIA & MECCANICA', 'INDUSTRY & ENGINEERING'),
   'tags': [d('INNOVATIV', 'INNOVATIVO', 'INNOVATIVE'), d('TECHNISCH', 'TECNICO', 'TECHNICAL'), d('INTERNATIONAL', 'INTERNAZIONALE', 'INTERNATIONAL')],
   'punkte': [('factory', d('Produkte und Lösungen\nprofessionell präsentieren', 'Prodotti e soluzioni\npresentati con professionalità', 'Products and solutions\nprofessionally presented')),
              ('box', d('3D-Modelle und Animationen', 'Modelli 3D e animazioni', '3D models and animations')),
              ('globe', d('Internationale Kunden erreichen', 'Raggiungere clienti internazionali', 'Reach international customers')),
              ('building-2', d('Starke Online-Präsenz für B2B', 'Presenza online forte per il B2B', 'Strong online presence for B2B'))],
   'slogan': d('Technik\ndigital\npräsentiert.', 'Tecnica\npresentata\nonline.', 'Engineering,\npresented\nonline.'),
   'leiste': [('box', d('3D-PRODUKTE', 'PRODOTTI 3D', '3D PRODUCTS')), ('download', d('DOWNLOADS', 'DOWNLOAD', 'DOWNLOADS')),
              ('search', d('SEO OPTIMIERT', 'SEO OTTIMIZZATO', 'SEO OPTIMISED')), ('languages', d('MEHRSPRACHIG', 'MULTILINGUE', 'MULTILINGUAL'))]},
 'c-landwirtschaft': {'f': 'c', 'g': 'handel', 'titel': d('LANDWIRTSCHAFT & AGRAR', 'AGRICOLTURA & AGROALIMENTARE', 'FARMING & AGRICULTURE'),
   'tags': [d('REGIONAL', 'LOCALE', 'LOCAL'), d('MODERN', 'MODERNO', 'MODERN'), d('ZUKUNFTSORIENTIERT', 'GUARDA AL FUTURO', 'FUTURE-MINDED')],
   'punkte': [('leaf', d('Produkte & Leistungen präsentieren', 'Prodotti e servizi in vetrina', 'Present products & services')),
              ('store', d('Hofladen und Direktverkauf online', 'Spaccio e vendita diretta online', 'Farm shop and direct sales online')),
              ('camera', d('Bilder & Videos aus Ihrem Betrieb', 'Foto e video della sua azienda', 'Photos & videos from your farm')),
              ('users', d('Mehr Kunden und regionale Sichtbarkeit', 'Più clienti e visibilità in zona', 'More customers and local visibility'))],
   'slogan': d('Tradition\ntrifft digitale\nZukunft.', 'La tradizione\nincontra il futuro\ndigitale.', 'Tradition\nmeets the digital\nfuture.'),
   'leiste': [('leaf', d('PRODUKTE', 'PRODOTTI', 'PRODUCTS')), ('store', d('HOFLÄDEN', 'SPACCI', 'FARM SHOPS')),
              ('search', d('SEO OPTIMIERT', 'SEO OTTIMIZZATO', 'SEO OPTIMISED')), ('monitor-smartphone', d('RESPONSIVE', 'RESPONSIVE', 'RESPONSIVE'))]},
 # ---------------------------------------------------------------- Stil D (Collage 4, 10 Stück)
 'd-handwerk': {'f': 'd', 'g': 'bau', 'titel': d('BAU & HANDWERK', 'EDILIZIA & ARTIGIANI', 'CONSTRUCTION & TRADES'),
   'tags': [d('MODERN', 'MODERNO', 'MODERN'), d('VERTRAUENSVOLL', 'AFFIDABILE', 'TRUSTWORTHY'), d('KUNDENSTARK', 'PIÙ CLIENTI', 'WINS CUSTOMERS')],
   'punkte': [('briefcase', d('Ihre Leistungen\nprofessionell präsentieren', 'I suoi servizi\npresentati con cura', 'Your services,\nprofessionally presented')),
              ('images', d('Vorher/Nachher-\nGalerie', 'Galleria\nprima/dopo', 'Before/after\ngallery')),
              ('mail', d('Angebotsanfragen\nonline', 'Richieste di\npreventivo online', 'Quote requests\nonline')),
              ('smartphone', d('Auf allen Geräten,\nmehr Verkäufe', 'Su ogni dispositivo,\npiù vendite', 'On every device,\nmore sales'))],
   'slogan': d('Ihre Projekte.\nDigital\nerlebbar.', 'I suoi progetti.\nDa vivere\nonline.', 'Your projects.\nExperienced\nonline.')},
 'd-immobilien': {'f': 'd', 'g': 'handel', 'titel': d('IMMOBILIEN', 'IMMOBILIARE', 'REAL ESTATE'),
   'tags': [d('EXKLUSIV', 'ESCLUSIVO', 'EXCLUSIVE'), d('INTERAKTIV', 'INTERATTIVO', 'INTERACTIVE'), d('VERKAUFSSTARK', 'CHE VENDE', 'SELLS WELL')],
   'punkte': [('house', d('Objekte perfekt in\nSzene setzen', 'Immobili presentati\nalla perfezione', 'Showcase properties\nperfectly')),
              ('rotate-3d', d('Virtuelle 3D-\nRundgänge', 'Tour virtuali\nin 3D', 'Virtual 3D\ntours')),
              ('map-pin', d('Standort & Lage\ninteraktiv', 'Posizione e zona\ninterattive', 'Interactive location\n& area')),
              ('smartphone', d('Mehr Anfragen,\nmehr Verkäufe', 'Più richieste,\npiù vendite', 'More enquiries,\nmore sales'))],
   'slogan': d('Immobilien\nbesser\npräsentieren.', 'Immobili\npresentati\nmeglio.', 'Present\nproperties\nbetter.')},
 'd-arztpraxis': {'f': 'd', 'g': 'gesundheit', 'hell': True, 'titel': d('ÄRZTE & PRAXEN', 'MEDICI & STUDI', 'DOCTORS & PRACTICES'),
   'tags': [d('MODERN', 'MODERNO', 'MODERN'), d('VERTRAUENSVOLL', 'AFFIDABILE', 'TRUSTWORTHY'), d('PATIENTENFREUNDLICH', 'VICINO AI PAZIENTI', 'PATIENT-FRIENDLY')],
   'punkte': [('stethoscope', d('Leistungen klar\nvorstellen', 'Prestazioni\nspiegate con chiarezza', 'Introduce services\nclearly')),
              ('calendar-check', d('Online-\nTerminbuchung', 'Prenotazione\nonline', 'Online\nbooking')),
              ('info', d('Wichtige\nInformationen', 'Informazioni\nimportanti', 'Important\ninformation')),
              ('smartphone', d('Auf allen Geräten\nperfekt', 'Perfetto su\nogni dispositivo', 'Perfect on\nevery device'))],
   'slogan': d('Vertrauen.\nKompetenz.\nDigital.', 'Fiducia.\nCompetenza.\nOnline.', 'Trust.\nExpertise.\nDigital.')},
 'd-beauty': {'f': 'd', 'g': 'gesundheit', 'titel': d('BEAUTY & KOSMETIK', 'BELLEZZA & ESTETICA', 'BEAUTY & COSMETICS'),
   'tags': [d('ELEGANT', 'ELEGANTE', 'ELEGANT'), d('SINNLICH', 'SENSUALE', 'SENSUAL'), d('KUNDENSTARK', 'PIÙ CLIENTI', 'WINS CLIENTS')],
   'punkte': [('sparkles', d('Ihre Behandlungen\nperfekt präsentieren', 'I suoi trattamenti\npresentati alla perfezione', 'Your treatments,\nperfectly presented')),
              ('calendar-check', d('Online-\nTerminbuchung', 'Prenotazione\nonline', 'Online\nbooking')),
              ('images', d('Galerien &\nVorher/Nachher', 'Gallerie e\nprima/dopo', 'Galleries &\nbefore/after')),
              ('heart', d('Mehr Neukunden', 'Più nuovi clienti', 'More new clients'))],
   'slogan': d('Schönheit.\nDigital\ninszeniert.', 'Bellezza.\nMessa in scena\nonline.', 'Beauty.\nStaged\nonline.')},
 'd-fitness': {'f': 'd', 'g': 'gesundheit', 'titel': d('FITNESS & WELLNESS', 'FITNESS & BENESSERE', 'FITNESS & WELLNESS'),
   'tags': [d('DYNAMISCH', 'DINAMICO', 'DYNAMIC'), d('MOTIVIEREND', 'MOTIVANTE', 'MOTIVATING'), d('MITGLIEDERSTARK', 'PIÙ ISCRITTI', 'GROWS MEMBERS')],
   'punkte': [('dumbbell', d('Kurse und Angebote\npräsentieren', 'Corsi e offerte\nin vetrina', 'Present classes\nand offers')),
              ('user-check', d('Online-\nAnmeldungen', 'Iscrizioni\nonline', 'Online\nsign-ups')),
              ('video', d('Trainingspläne &\nVideos', 'Schede di allenamento\ne video', 'Training plans\n& videos')),
              ('users', d('Mehr Mitglieder', 'Più iscritti', 'More members'))],
   'slogan': d('Stärker.\nSichtbarer.\nDigital.', 'Più forti.\nPiù visibili.\nOnline.', 'Stronger.\nMore visible.\nDigital.')},
 'd-restaurant': {'f': 'd', 'g': 'gast', 'titel': d('RESTAURANTS', 'RISTORANTI', 'RESTAURANTS'),
   'tags': [d('GENUSS', 'GUSTO', 'FLAVOUR'), d('APPETITLICH', 'INVITANTE', 'APPETISING'), d('RESERVIERUNGSSTARK', 'PIÙ PRENOTAZIONI', 'FILLS TABLES')],
   'punkte': [('utensils', d('Speisekarten digital\nund aktuell', 'Menù online\nsempre aggiornati', 'Menus online\nand up to date')),
              ('calendar-check', d('Online-\nReservierungen', 'Prenotazioni\nonline', 'Online\nreservations')),
              ('rotate-3d', d('Atmosphäre in Bildern\nund 3D', 'Atmosfera in foto\ne in 3D', 'Atmosphere in photos\nand 3D')),
              ('users', d('Mehr Gäste', 'Più ospiti', 'More guests'))],
   'slogan': d('Mehr als\neine Website.\nEin Erlebnis.', 'Più di\nun sito.\nUn’esperienza.', 'More than\na website.\nAn experience.')},
 'd-hotel': {'f': 'd', 'g': 'gast', 'titel': d('HOTELS & FERIENWOHNUNGEN', 'HOTEL & CASE VACANZA', 'HOTELS & HOLIDAY HOMES'),
   'tags': [d('EINLADEND', 'ACCOGLIENTE', 'INVITING'), d('EMOTIONAL', 'EMOZIONALE', 'EMOTIONAL'), d('BUCHUNGSSTARK', 'PIÙ PRENOTAZIONI', 'BOOKS WELL')],
   'punkte': [('bed-double', d('Zimmer & Angebote\npräsentieren', 'Camere e offerte\nin vetrina', 'Present rooms\n& offers')),
              ('calendar-check', d('Online-\nBuchungssystem', 'Sistema di\nprenotazione online', 'Online\nbooking system')),
              ('rotate-3d', d('360°-Rundgänge', 'Tour a 360°', '360° tours')),
              ('trending-up', d('Mehr Buchungen', 'Più prenotazioni', 'More bookings'))],
   'slogan': d('Urlaub.\nBeginnt schon vor\nder Anreise.', 'La vacanza\ninizia già prima\ndell’arrivo.', 'Holidays\nbegin before\nyou arrive.')},
 'd-logistik': {'f': 'd', 'g': 'handel', 'titel': d('LOGISTIK & TRANSPORT', 'LOGISTICA & TRASPORTI', 'LOGISTICS & TRANSPORT'),
   'tags': [d('MODERN', 'MODERNO', 'MODERN'), d('PROFESSIONELL', 'PROFESSIONALE', 'PROFESSIONAL'), d('VERTRAUENSWÜRDIG', 'AFFIDABILE', 'TRUSTWORTHY')],
   'punkte': [('truck', d('Ihre Leistungen klar\npräsentieren', 'I suoi servizi\nspiegati con chiarezza', 'Present your services\nclearly')),
              ('map-pin', d('Touren & Standorte\nzeigen', 'Tratte e sedi\nin evidenza', 'Show routes\n& locations')),
              ('mail', d('Anfragen leicht\ngemacht', 'Richieste\nsemplici', 'Enquiries\nmade easy')),
              ('smartphone', d('Auf allen Geräten\nperfekt', 'Perfetto su\nogni dispositivo', 'Perfect on\nevery device'))],
   'slogan': d('In Bewegung.\nDigital\nstärker.', 'In movimento.\nOnline\npiù forti.', 'On the move.\nStronger\nonline.')},
 'd-kanzlei': {'f': 'd', 'g': 'beratung', 'titel': d('ANWÄLTE & KANZLEIEN', 'AVVOCATI & STUDI LEGALI', 'LAWYERS & LAW FIRMS'),
   'tags': [d('SERIÖS', 'SERIO', 'SERIOUS'), d('ÜBERSICHTLICH', 'CHIARO', 'CLEAR'), d('MANDANTENSTARK', 'PIÙ CLIENTI', 'WINS CLIENTS')],
   'punkte': [('scale', d('Rechtsgebiete klar\ndarstellen', 'Aree del diritto\nspiegate con chiarezza', 'Practice areas\nclearly presented')),
              ('users', d('Kompetenz und\nTeam vorstellen', 'Competenza\ne team in primo piano', 'Introduce expertise\nand team')),
              ('mail', d('Einfache\nKontaktaufnahme', 'Contatto\nsemplice', 'Easy\nto get in touch')),
              ('user-check', d('Mehr Mandanten', 'Più clienti', 'More clients'))],
   'slogan': d('Vertrauen.\nKompetenz.\nSichtbar.', 'Fiducia.\nCompetenza.\nVisibili.', 'Trust.\nExpertise.\nVisible.')},
 'd-solar': {'f': 'd', 'g': 'bau', 'titel': d('SOLAR & ENERGIE', 'SOLARE & ENERGIA', 'SOLAR & ENERGY'),
   'tags': [d('MODERN', 'MODERNO', 'MODERN'), d('ÜBERZEUGEND', 'CONVINCENTE', 'CONVINCING'), d('ZUKUNFTSSTARK', 'GUARDA AL FUTURO', 'FUTURE-READY')],
   'punkte': [('sun', d('Ihre Lösungen anschaulich\npräsentieren', 'Le sue soluzioni\nspiegate con chiarezza', 'Present your solutions\nvividly')),
              ('badge-euro', d('Förderungen und\nVorteile erklären', 'Incentivi e vantaggi\nspiegati', 'Explain subsidies\nand benefits')),
              ('images', d('Projekte und\nReferenzen zeigen', 'Progetti e\nreferenze in mostra', 'Show projects\nand references')),
              ('message-square', d('Mehr Anfragen', 'Più richieste', 'More enquiries'))],
   'slogan': d('Heute nachhaltig.\nMorgen stärker.', 'Oggi sostenibili.\nDomani più forti.', 'Sustainable today.\nStronger tomorrow.')},
}
