<?php
declare(strict_types=1);
/* Automatisch erzeugt aus den Flyer-Vorlagen (28.09.2026). Feld q = weiße QR-Fläche [x, y, b, h] in Pixeln. */
return [
    'allgemein' => ['g' => 'allgemein', 'n' => ['de' => 'Allgemein', 'it' => 'Generale', 'en' => 'General'], 'b' => 1024, 'h' => 1536, 'q' => [897, 1370, 83, 87]],
    'allgemein-2' => ['g' => 'allgemein', 'n' => ['de' => 'Allgemein 2', 'it' => 'Generale 2', 'en' => 'General 2'], 'b' => 709, 'h' => 1064, 'q' => [609, 953, 65, 65]],
    'handwerk' => ['g' => 'bau', 'n' => ['de' => 'Handwerk & Bau', 'it' => 'Artigiani & edilizia', 'en' => 'Trades & construction'], 'b' => 948, 'h' => 1659, 'q' => [816, 1511, 81, 81]],
    'garten' => ['g' => 'bau', 'n' => ['de' => 'Garten- & Landschaftsbau', 'it' => 'Giardinaggio & paesaggio', 'en' => 'Gardening & landscaping'], 'b' => 1024, 'h' => 1536, 'q' => [888, 1388, 90, 92]],
    'reinigung' => ['g' => 'bau', 'n' => ['de' => 'Gebäudereinigung', 'it' => 'Imprese di pulizia', 'en' => 'Cleaning services'], 'b' => 1024, 'h' => 1536, 'q' => [889, 1397, 93, 95]],
    'architektur' => ['g' => 'bau', 'n' => ['de' => 'Architektur & Planung', 'it' => 'Architettura & progettazione', 'en' => 'Architecture & planning'], 'b' => 1122, 'h' => 1402, 'q' => [973, 1254, 94, 93]],
    'solar' => ['g' => 'bau', 'n' => ['de' => 'Solar & Photovoltaik', 'it' => 'Solare & fotovoltaico', 'en' => 'Solar & photovoltaics'], 'b' => 948, 'h' => 1659, 'q' => [811, 1377, 88, 87]],
    'energie' => ['g' => 'bau', 'n' => ['de' => 'Energie & Wärmepumpen', 'it' => 'Energia & pompe di calore', 'en' => 'Energy & heat pumps'], 'b' => 1122, 'h' => 1402, 'q' => [948, 1231, 107, 108]],
    'arztpraxis' => ['g' => 'gesundheit', 'n' => ['de' => 'Arztpraxis', 'it' => 'Studio medico', 'en' => 'Medical practice'], 'b' => 948, 'h' => 1659, 'q' => [818, 1510, 84, 86]],
    'zahnarzt' => ['g' => 'gesundheit', 'n' => ['de' => 'Arzt- & Zahnarztpraxis', 'it' => 'Studio medico & dentistico', 'en' => 'Doctor & dentist'], 'b' => 941, 'h' => 1672, 'q' => [833, 1489, 72, 78]],
    'pflege' => ['g' => 'gesundheit', 'n' => ['de' => 'Pflegedienst', 'it' => 'Assistenza & cura', 'en' => 'Care services'], 'b' => 1122, 'h' => 1402, 'q' => [977, 1249, 95, 97]],
    'kosmetik' => ['g' => 'gesundheit', 'n' => ['de' => 'Kosmetik & Beauty', 'it' => 'Estetica & bellezza', 'en' => 'Beauty & cosmetics'], 'b' => 948, 'h' => 1659, 'q' => [825, 1477, 87, 86]],
    'fitness' => ['g' => 'gesundheit', 'n' => ['de' => 'Fitness & Sport', 'it' => 'Fitness & sport', 'en' => 'Fitness & sports'], 'b' => 941, 'h' => 1672, 'q' => [823, 1492, 84, 84]],
    'restaurant' => ['g' => 'gast', 'n' => ['de' => 'Restaurant & Café', 'it' => 'Ristorante & bar', 'en' => 'Restaurant & café'], 'b' => 948, 'h' => 1659, 'q' => [827, 1529, 80, 84]],
    'hotel' => ['g' => 'gast', 'n' => ['de' => 'Hotel & Ferienwohnung', 'it' => 'Hotel & casa vacanze', 'en' => 'Hotel & holiday home'], 'b' => 941, 'h' => 1672, 'q' => [818, 1498, 83, 86]],
    'tourismus' => ['g' => 'gast', 'n' => ['de' => 'Tourismus & Ausflüge', 'it' => 'Turismo & escursioni', 'en' => 'Tourism & tours'], 'b' => 941, 'h' => 1672, 'q' => [826, 1498, 80, 89]],
    'events' => ['g' => 'gast', 'n' => ['de' => 'Events & Hochzeiten', 'it' => 'Eventi & matrimoni', 'en' => 'Events & weddings'], 'b' => 941, 'h' => 1672, 'q' => [824, 1493, 80, 87]],
    'steuerberater' => ['g' => 'beratung', 'n' => ['de' => 'Steuerberatung & Buchhaltung', 'it' => 'Commercialista & contabilità', 'en' => 'Tax & accounting'], 'b' => 1122, 'h' => 1402, 'q' => [974, 1266, 90, 94]],
    'kanzlei' => ['g' => 'beratung', 'n' => ['de' => 'Rechtsanwälte & Kanzlei', 'it' => 'Avvocati & studio legale', 'en' => 'Lawyers & law firm'], 'b' => 1122, 'h' => 1402, 'q' => [981, 1234, 99, 101]],
    'finanz' => ['g' => 'beratung', 'n' => ['de' => 'Versicherung & Finanzen', 'it' => 'Assicurazioni & finanza', 'en' => 'Insurance & finance'], 'b' => 1024, 'h' => 1536, 'q' => [892, 1389, 96, 99]],
    'it' => ['g' => 'beratung', 'n' => ['de' => 'IT & Software', 'it' => 'IT & software', 'en' => 'IT & software'], 'b' => 1024, 'h' => 1536, 'q' => [885, 1381, 97, 95]],
    'shop' => ['g' => 'handel', 'n' => ['de' => 'Online-Shop & Einzelhandel', 'it' => 'Negozio online & commercio', 'en' => 'Online shop & retail'], 'b' => 941, 'h' => 1672, 'q' => [826, 1484, 72, 75]],
    'autohaus' => ['g' => 'handel', 'n' => ['de' => 'Autohaus & Werkstatt', 'it' => 'Concessionaria & officina', 'en' => 'Car dealer & garage'], 'b' => 941, 'h' => 1672, 'q' => [830, 1515, 74, 75]],
    'logistik' => ['g' => 'handel', 'n' => ['de' => 'Logistik & Transport', 'it' => 'Logistica & trasporti', 'en' => 'Logistics & transport'], 'b' => 948, 'h' => 1659, 'q' => [820, 1494, 85, 85]],
    'logistik-2' => ['g' => 'handel', 'n' => ['de' => 'Logistik & Transport 2', 'it' => 'Logistica & trasporti 2', 'en' => 'Logistics & transport 2'], 'b' => 1122, 'h' => 1402, 'q' => [980, 1262, 103, 105]],
    'foto' => ['g' => 'kreativ', 'n' => ['de' => 'Fotografie & Video', 'it' => 'Fotografia & video', 'en' => 'Photo & video'], 'b' => 1024, 'h' => 1536, 'q' => [883, 1374, 90, 91]],
    'kuenstler' => ['g' => 'kreativ', 'n' => ['de' => 'Künstler & Kreative', 'it' => 'Artisti & creativi', 'en' => 'Artists & creatives'], 'b' => 941, 'h' => 1672, 'q' => [822, 1489, 81, 83]],
    'verein' => ['g' => 'kreativ', 'n' => ['de' => 'Vereine & Clubs', 'it' => 'Associazioni & club', 'en' => 'Clubs & associations'], 'b' => 941, 'h' => 1672, 'q' => [828, 1476, 74, 77]],
    'bildung' => ['g' => 'kreativ', 'n' => ['de' => 'Kurse & Bildung', 'it' => 'Corsi & formazione', 'en' => 'Courses & education'], 'b' => 941, 'h' => 1672, 'q' => [822, 1433, 86, 87]],
];
