<?php
declare(strict_types=1);
/* Automatisch erzeugt (tools/werbemittel/gen.py). Einheit 1/10 mm auf der Leinwand mit Beschnitt; Felder wie bei den Visitenkarten. */
return [
    'b' => 105,
    'h' => 148,
    'beschnitt' => 3,
    'einseitig' => false,
    'gross' => false,
    'stile' => [
        'a' => [
            'titel' => [
                'x' => 555,
                'y1' => 942,
                'y2' => 1024,
                'size' => 69,
                'font' => 700,
                'farbe1' => '#f6f1e6',
                'farbe2' => '#e6b85c',
                'max' => 932,
            ],
            'qr' => [366.3, 360.0, 377.4],
            'name' => [
                'x' => 178,
                'y' => 1029,
                'size' => 43,
                'font' => 700,
                'farbe' => '#f6f1e6',
                'max' => 755,
            ],
            'link' => [
                'x' => 231,
                'y' => 1094,
                'size' => 29,
                'font' => 500,
                'farbe' => '#f6f1e6',
                'max' => 701,
            ],
            'kontakt' => [
                'x' => 231,
                'y' => 1160,
                'size' => 29,
                'font' => 500,
                'farbe' => '#f6f1e6',
                'max' => 701,
            ],
        ],
        'b' => [
            'titel' => [
                'x' => 555,
                'y1' => 942,
                'y2' => 1024,
                'size' => 69,
                'font' => 700,
                'farbe1' => '#f6f1e6',
                'farbe2' => '#e6b85c',
                'max' => 932,
            ],
            'qr' => [366.3, 360.0, 377.4],
            'name' => [
                'x' => 178,
                'y' => 1029,
                'size' => 43,
                'font' => 700,
                'farbe' => '#f6f1e6',
                'max' => 755,
            ],
            'link' => [
                'x' => 231,
                'y' => 1094,
                'size' => 29,
                'font' => 500,
                'farbe' => '#f6f1e6',
                'max' => 701,
            ],
            'kontakt' => [
                'x' => 231,
                'y' => 1160,
                'size' => 29,
                'font' => 500,
                'farbe' => '#f6f1e6',
                'max' => 701,
            ],
        ],
        'c' => [
            'titel' => [
                'x' => 555,
                'y1' => 942,
                'y2' => 1024,
                'size' => 69,
                'font' => 700,
                'farbe1' => '#f6f1e6',
                'farbe2' => '#e6b85c',
                'max' => 932,
            ],
            'qr' => [366.3, 360.0, 377.4],
            'name' => [
                'x' => 178,
                'y' => 1029,
                'size' => 43,
                'font' => 700,
                'farbe' => '#f6f1e6',
                'max' => 755,
            ],
            'link' => [
                'x' => 231,
                'y' => 1094,
                'size' => 29,
                'font' => 500,
                'farbe' => '#f6f1e6',
                'max' => 701,
            ],
            'kontakt' => [
                'x' => 231,
                'y' => 1160,
                'size' => 29,
                'font' => 500,
                'farbe' => '#f6f1e6',
                'max' => 701,
            ],
        ],
        'd' => [
            'titel' => [
                'x' => 555,
                'y1' => 942,
                'y2' => 1024,
                'size' => 69,
                'font' => 700,
                'farbe1' => '#1f1a13',
                'farbe2' => '#9a6f25',
                'max' => 932,
            ],
            'qr' => [366.3, 360.0, 377.4],
            'name' => [
                'x' => 178,
                'y' => 1029,
                'size' => 43,
                'font' => 700,
                'farbe' => '#1f1a13',
                'max' => 755,
            ],
            'link' => [
                'x' => 231,
                'y' => 1094,
                'size' => 29,
                'font' => 500,
                'farbe' => '#1f1a13',
                'max' => 701,
            ],
            'kontakt' => [
                'x' => 231,
                'y' => 1160,
                'size' => 29,
                'font' => 500,
                'farbe' => '#1f1a13',
                'max' => 701,
            ],
        ],
    ],
];
