-- 175: Partnerbereich duzt (05.10.2026, Uwe: „du“ im ganzen Partnerbereich).
-- Die Produkttexte im Marketing Center sprechen den Partner an. Ersetzt wird nur der
-- wörtliche alte Satz — ein von Uwe in der Verwaltung umgeschriebener Text bleibt.
UPDATE wm_produkte SET text_de = 'Mit deinem Namen, deiner Partner-ID und dem QR-Code zu deiner Seite.' WHERE vorlage = 'visitenkarte' AND text_de = 'Mit Ihrem Namen, Ihrer Partner-ID und dem QR-Code zu Ihrer Seite.';
UPDATE wm_produkte SET text_de = 'Vorderseite: Vecom Design. Rückseite: dein Name, dein Kontakt und der QR-Code zu deiner Seite.' WHERE vorlage = 'flyer_a6' AND text_de = 'Vorderseite: Vecom Design. Rückseite: Ihr Name, Ihr Kontakt und der QR-Code zu Ihrer Seite.';
UPDATE wm_produkte SET text_de = 'Vorderseite: Vecom Design. Rückseite: dein Name, dein Kontakt und der QR-Code zu deiner Seite.' WHERE vorlage = 'flyer_a5' AND text_de = 'Vorderseite: Vecom Design. Rückseite: Ihr Name, Ihr Kontakt und der QR-Code zu Ihrer Seite.';
UPDATE wm_produkte SET text_de = 'Vorderseite: einer der 51 Branchen-Flyer, auf Deutsch, Italienisch oder Englisch, mit deinem QR-Code und deinem Link. Rückseite: dein Name, dein Kontakt und der QR-Code zu deiner Seite.' WHERE vorlage = 'flyer_branche' AND text_de = 'Vorderseite: einer der 51 Branchen-Flyer, auf Deutsch, Italienisch oder Englisch, mit Ihrem QR-Code und Ihrem Link. Rückseite: Ihr Name, Ihr Kontakt und der QR-Code zu Ihrer Seite.';
UPDATE wm_produkte SET text_de = 'Outdoor-Aufkleber mit deinem QR-Code: für Schaufenster, Auto, Laptop. Wer scannt, landet auf deiner Seite.' WHERE vorlage = 'aufkleber_50' AND text_de = 'Outdoor-Aufkleber mit Ihrem QR-Code: für Schaufenster, Auto, Laptop. Wer scannt, landet auf Ihrer Seite.';
UPDATE wm_produkte SET text_de = 'Roll-up mit Tasche: Vecom-Logo, unsere Leistungen und dein großer QR-Code mit deinem Link. Für Messen, Geschäfte, Büros.' WHERE vorlage = 'rollup_85' AND text_de = 'Roll-up mit Tasche: Vecom-Logo, unsere Leistungen und Ihr großer QR-Code mit Ihrem Link. Für Messen, Geschäfte, Büros.';
UPDATE wm_produkte SET text_de = '12 Monate, 12 Ideen für den digitalen Auftritt — mit deinem Namen und QR-Code auf jeder Seite. Ein Geschenk, das ein Jahr lang im Betrieb hängt.' WHERE vorlage = 'kalender_a3' AND text_de = '12 Monate, 12 Ideen für den digitalen Auftritt — mit Ihrem Namen und QR-Code auf jeder Seite. Ein Geschenk, das ein Jahr lang im Betrieb hängt.';
UPDATE wm_produkte SET text_de = 'Weiße Keramiktasse, spülmaschinenfest: auf der einen Seite das Vecom-Zeichen, auf der anderen dein Name und QR-Code. Ein Geschenk, das jeden Tag benutzt wird.' WHERE vorlage = 'tasse_11' AND text_de = 'Weiße Keramiktasse, spülmaschinenfest: auf der einen Seite das Vecom-Zeichen, auf der anderen Ihr Name und QR-Code. Ein Geschenk, das jeden Tag benutzt wird.';
UPDATE wm_produkte SET text_de = 'Spiralnotizbuch 14,5 × 21 cm, 140 gepunktete Seiten: vorn das Vecom-Zeichen, hinten dein Name und QR-Code. Bleibt beim Kunden auf dem Schreibtisch.' WHERE vorlage = 'notizbuch' AND text_de = 'Spiralnotizbuch 14,5 × 21 cm, 140 gepunktete Seiten: vorn das Vecom-Zeichen, hinten Ihr Name und QR-Code. Bleibt beim Kunden auf dem Schreibtisch.';
UPDATE wm_produkte SET text_de = 'Doppelwandige Edelstahlflasche, weiß glänzend: rundum das Vecom-Zeichen, dein Name und QR-Code. Hält Getränke warm oder kalt.' WHERE vorlage = 'flasche' AND text_de = 'Doppelwandige Edelstahlflasche, weiß glänzend: rundum das Vecom-Zeichen, Ihr Name und QR-Code. Hält Getränke warm oder kalt.';
UPDATE wm_produkte SET text_de = 'Untersetzer 95 × 95 mm, hochglänzend mit Kork-Rücken: Vecom-Zeichen, dein Name und QR-Code — für Theke, Bar und Wartebereich.' WHERE vorlage = 'untersetzer' AND text_de = 'Untersetzer 95 × 95 mm, hochglänzend mit Kork-Rücken: Vecom-Zeichen, Ihr Name und QR-Code — für Theke, Bar und Wartebereich.';
UPDATE wm_produkte SET text_de = 'Schwarze Tragetasche aus Bio-Baumwolle, 40,6 × 35,6 cm: vorn das Vecom-Zeichen in Gold, dein Name und QR-Code. Ein Geschenk, das durch die Stadt getragen wird.' WHERE vorlage = 'beutel' AND text_de = 'Schwarze Tragetasche aus Bio-Baumwolle, 40,6 × 35,6 cm: vorn das Vecom-Zeichen in Gold, Ihr Name und QR-Code. Ein Geschenk, das durch die Stadt getragen wird.';
