<?php
declare(strict_types=1);
/* Automatisch erzeugt (tools/werbemittel/gen.py). Einheit 1/10 mm auf der Leinwand mit Beschnitt; Felder wie bei den Visitenkarten. */
return [
    'b' => 148,
    'h' => 210,
    'beschnitt' => 3,
    'einseitig' => false,
    'gross' => false,
    'stile' => [
        'a' => [
            'titel' => [
                'x' => 770,
                'y1' => 1309,
                'y2' => 1423,
                'size' => 95,
                'font' => 700,
                'farbe1' => '#f6f1e6',
                'farbe2' => '#e6b85c',
                'max' => 1294,
            ],
            'qr' => [508.2, 490.4, 523.6],
            'name' => [
                'x' => 246,
                'y' => 1418,
                'size' => 59,
                'font' => 700,
                'farbe' => '#f6f1e6',
                'max' => 1047,
            ],
            'link' => [
                'x' => 321,
                'y' => 1509,
                'size' => 40,
                'font' => 500,
                'farbe' => '#f6f1e6',
                'max' => 973,
            ],
            'kontakt' => [
                'x' => 321,
                'y' => 1600,
                'size' => 40,
                'font' => 500,
                'farbe' => '#f6f1e6',
                'max' => 973,
            ],
        ],
        'b' => [
            'titel' => [
                'x' => 770,
                'y1' => 1309,
                'y2' => 1423,
                'size' => 95,
                'font' => 700,
                'farbe1' => '#f6f1e6',
                'farbe2' => '#e6b85c',
                'max' => 1294,
            ],
            'qr' => [508.2, 490.4, 523.6],
            'name' => [
                'x' => 246,
                'y' => 1418,
                'size' => 59,
                'font' => 700,
                'farbe' => '#f6f1e6',
                'max' => 1047,
            ],
            'link' => [
                'x' => 321,
                'y' => 1509,
                'size' => 40,
                'font' => 500,
                'farbe' => '#f6f1e6',
                'max' => 973,
            ],
            'kontakt' => [
                'x' => 321,
                'y' => 1600,
                'size' => 40,
                'font' => 500,
                'farbe' => '#f6f1e6',
                'max' => 973,
            ],
        ],
        'c' => [
            'titel' => [
                'x' => 770,
                'y1' => 1309,
                'y2' => 1423,
                'size' => 95,
                'font' => 700,
                'farbe1' => '#f6f1e6',
                'farbe2' => '#e6b85c',
                'max' => 1294,
            ],
            'qr' => [508.2, 490.4, 523.6],
            'name' => [
                'x' => 246,
                'y' => 1418,
                'size' => 59,
                'font' => 700,
                'farbe' => '#f6f1e6',
                'max' => 1047,
            ],
            'link' => [
                'x' => 321,
                'y' => 1509,
                'size' => 40,
                'font' => 500,
                'farbe' => '#f6f1e6',
                'max' => 973,
            ],
            'kontakt' => [
                'x' => 321,
                'y' => 1600,
                'size' => 40,
                'font' => 500,
                'farbe' => '#f6f1e6',
                'max' => 973,
            ],
        ],
        'd' => [
            'titel' => [
                'x' => 770,
                'y1' => 1309,
                'y2' => 1423,
                'size' => 95,
                'font' => 700,
                'farbe1' => '#1f1a13',
                'farbe2' => '#9a6f25',
                'max' => 1294,
            ],
            'qr' => [508.2, 490.4, 523.6],
            'name' => [
                'x' => 246,
                'y' => 1418,
                'size' => 59,
                'font' => 700,
                'farbe' => '#1f1a13',
                'max' => 1047,
            ],
            'link' => [
                'x' => 321,
                'y' => 1509,
                'size' => 40,
                'font' => 500,
                'farbe' => '#1f1a13',
                'max' => 973,
            ],
            'kontakt' => [
                'x' => 321,
                'y' => 1600,
                'size' => 40,
                'font' => 500,
                'farbe' => '#1f1a13',
                'max' => 973,
            ],
        ],
    ],
];
